- name: general software
  hosts: localhost
  become: yes

  tasks:
    - snap:
        name: "{{ item }}" 
        state: present
      loop:
        - brave
        - signal-desktop
    - snap: 
        name: nvim
        classic: true
    - apt: 
        name: zsh
    - shell: 
        cmd: chsh -s $(which zsh)
    - shell:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

