- name: general software
  hosts: localhost
  become: yes

  tasks:
    - snap:
        name: "{{ name }}"
        state: present
      loop:
        - brave
        - signal-desktop
        - vlc
        - --classic neovim
